# Generated by Django 3.1.5 on 2021-02-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210117_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='header_image_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=6, null=True),
        ),
    ]
