# Generated by Django 3.1.4 on 2021-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210102_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingpage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Page display title. Overwrites the default title.', max_length=100, null=True),
        ),
    ]
