# Generated by Django 3.2.12 on 2022-03-10 15:26

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['title'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.RenameField(
            model_name='blogcategory',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
    ]
