# Generated by Django 3.1.4 on 2021-01-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testimonialcarousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='section_1_content',
            new_name='bio_content',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='section_1_heading',
            new_name='bio_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='section_1_subheading',
            new_name='bio_subheading',
        ),
    ]
