# Generated by Django 3.1.4 on 2021-01-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210102_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='section_2_content',
            new_name='speaker_content',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='section_2_heading',
            new_name='speaker_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='section_2_subheading',
            new_name='speaker_subheading',
        ),
    ]
