# Generated by Django 3.1.5 on 2021-02-01 05:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0012_auto_20210113_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='bio_content',
            new_name='content_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='speaker_content',
            new_name='content_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bio_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bio_subheading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_author',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_quote',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='speaker_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='speaker_subheading',
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_1_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_2_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='IamList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article', models.CharField(choices=[('', 'none'), ('a', 'A'), ('an', 'An'), ('the', 'The')], default='a', max_length=4, null=True)),
                ('descriptor', models.CharField(max_length=25, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
