# Generated by Django 3.1.14 on 2022-02-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210201_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='quote',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='iamlist',
            name='descriptor',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
