# Generated by Django 3.1.14 on 2022-02-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220228_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='quote_background_image',
            new_name='content_1_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image_1_position',
        ),
    ]
