# Generated by Django 3.1.14 on 2022-03-01 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0016_homepage_content_1_text_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image_2_position',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_1_text_color',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_2_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_2_text_color',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_2_text_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_1_text_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=6, null=True),
        ),
    ]
