# Generated by Django 3.1.14 on 2022-03-02 01:00

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0018_auto_20220301_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='quote',
            new_name='quote_1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_3',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(required=False))])), ('button', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(required=True)), ('button_style', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[('btn', 'Standard'), ('btn-outline', 'Outline')])), ('button_page', wagtail.core.blocks.PageChooserBlock(help_text='Page overrides URL if one is chosen.', required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])), ('headline', wagtail.core.blocks.StructBlock([('headline_text', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_3_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_3_text_color',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_3_text_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
