# Generated by Django 3.1.4 on 2021-01-06 00:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_auto_20210106_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presspagesection',
            options={},
        ),
        migrations.RemoveField(
            model_name='presspagesection',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='presslink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_link', to='flex.presspagesection'),
        ),
    ]
