# Generated by Django 3.1.4 on 2021-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_auto_20210106_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presslink',
            name='link_text',
            field=models.CharField(max_length=100),
        ),
    ]
