# Generated by Django 3.1.4 on 2021-01-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('flex', '0007_auto_20210107_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
