# Generated by Django 3.1.4 on 2021-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0008_flexpage_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='presspage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Page display title. Overwrites the default title.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presspage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Page display title. Overwrites the default title.', max_length=100, null=True),
        ),
    ]
