# Generated by Django 3.1.5 on 2021-01-18 16:04

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0014_auto_20210118_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='presspage',
            name='carousel_content',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock()), ('headline', wagtail.core.blocks.StructBlock([('headline_text', wagtail.core.blocks.CharBlock(required=True))])), ('image_carousel', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(max_length=100, required=False))]))), ('show_download_links', wagtail.core.blocks.BooleanBlock(default=False, required=True))]))], blank=True, null=True),
        ),
    ]
