# Generated by Django 3.1.5 on 2021-08-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0017_landingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageBiz',
            fields=[
                ('landingpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex.landingpage')),
            ],
            options={
                'verbose_name': 'Landing Page (biz)',
                'verbose_name_plural': 'Landing Pages (biz)',
            },
            bases=('flex.landingpage',),
        ),
    ]
