# Generated by Django 3.1.5 on 2021-09-04 22:30

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('flex', '0018_landingpagebiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(blank=True, help_text='Page display title. Overwrites the default title.', max_length=100, null=True)),
                ('video_embed_code', models.TextField(blank=True, help_text='Paste Wistia embed code here.', null=True)),
                ('content', wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(required=False))])), ('button', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(required=True)), ('button_style', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[('btn', 'Standard'), ('btn-outline', 'Outline')])), ('button_page', wagtail.core.blocks.PageChooserBlock(help_text='Page overrides URL if one is chosen.', required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])), ('headline', wagtail.core.blocks.StructBlock([('headline_text', wagtail.core.blocks.CharBlock(required=True))])), ('left_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(required=False))])), ('image_row', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_1_caption', wagtail.core.blocks.CharBlock(required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_2_caption', wagtail.core.blocks.CharBlock(required=False)), ('image_3', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_3_caption', wagtail.core.blocks.CharBlock(required=False)), ('image_4', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_4_caption', wagtail.core.blocks.CharBlock(required=False))])), ('image_carousel', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(max_length=100, required=False))]))), ('show_download_links', wagtail.core.blocks.BooleanBlock(default=False, required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exclusive Page',
                'verbose_name_plural': 'Exclusive Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
