# Generated by Django 3.1.14 on 2022-01-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('flex', '0019_exclusivecontentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(blank=True, help_text='Page display title. Overwrites the default title.', max_length=100, null=True)),
                ('webinar_date', models.DateTimeField(null=True)),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Webinar Page',
                'verbose_name_plural': 'Webinar Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
