# Generated by Django 3.1.14 on 2022-01-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0020_webinarpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarpage',
            name='mailchimp_list_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webinarpage',
            name='mailchimp_tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
