# Generated by Django 3.1.14 on 2022-01-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('flex', '0021_auto_20220103_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(default='Self-Advocate Audaciously', max_length=100, null=True)),
                ('program_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Program Page',
                'verbose_name_plural': 'Program Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='webinarpage',
            name='header_image',
        ),
        migrations.AlterField(
            model_name='webinarpage',
            name='mailchimp_list_id',
            field=models.CharField(default='314c20dfea', max_length=20),
        ),
    ]
