# Generated by Django 3.2.12 on 2022-05-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('flex', '0023_auto_20220105_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlySensitiveRadical',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(default='Becoming a Highly Sensitive Radical', max_length=100, null=True)),
                ('program_price', models.DecimalField(decimal_places=2, default=129.0, max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'HSR Page',
                'verbose_name_plural': 'HSR Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
