# Generated by Django 3.1.4 on 2020-12-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Intagram URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube Channel', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', null=True)),
                ('medium', models.URLField(blank=True, help_text='Medium URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
