# Generated by Django 3.1.5 on 2021-09-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('buyer_first_name', models.CharField(max_length=100, null=True)),
                ('buyer_last_name', models.CharField(max_length=100, null=True)),
                ('buyer_email', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'PayPal Transaction',
                'verbose_name_plural': 'PayPal Transactions',
            },
        ),
    ]
